# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'list.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import json
import threading
from PyQt5 import QtCore, QtGui, QtWidgets
from ctypes import *
from PyQt5.QtWidgets import QAbstractItemView
from Script.extractor import NumberExtractor
from Script.music import main as mn


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.WIGHT, self.HEIGHT = self.screen_size()
        MainWindow.resize(self.WIGHT, self.HEIGHT - 100)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.listView.setGeometry(QtCore.QRect(0, 0, self.WIGHT, self.HEIGHT - 100))
        self.listView.setStyleSheet("font: 12pt;")
        self.listView.setObjectName("listView")
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def get_name_window(self, name_window):
        self.NAME_WINDOW = name_window
        return self.NAME_WINDOW

    def set_name_window(self):
        return self.NAME_WINDOW

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(self.set_name_window(), self.set_name_window()))

    def Print(self, list):
        model = QtGui.QStandardItemModel()
        self.listView.setModel(model)
        self.number = 0
        for i in list:
            self.number += 1
            self.str = str(self.number) + " -> " + i
            item = QtGui.QStandardItem(self.str)
            model.appendRow(item)

    def screen_size(self):
        self.HEIGHT = windll.user32.GetSystemMetrics(1)
        self.WIGHT = windll.user32.GetSystemMetrics(0)
        return self.WIGHT, self.HEIGHT


def Print_list(name_file):
    type_file = name_file.replace("Files/", '')
    type_file = type_file.split(".")
    try:
        if type_file[0] == "installed_files":
            with open(name_file) as file:
                array = [row.strip() for row in file]
            return array
        if type_file[0] == "music":
            with open(name_file, "r") as file:
                temp = json.load(file)
                array = [row['Name'] for row in temp["music"]]
            return array
        if type_file[0] == "tasklist":
            with open(name_file) as file:
                array = [row.strip() for row in file]
            return array
    except FileNotFoundError:
        from Jora import Jora
        jora = Jora()
        jora.Speak("Такого файла не существует")
        pass


def main(name_file):
    import sys
    name_window = name_file.split(".")
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.get_name_window(name_window[0])
    ui.setupUi(MainWindow)
    ui.Print(Print_list(name_file))
    MainWindow.show()
    app.exec_()



